import "server-only";
import crypto from "node:crypto";
import type {CreatePaymentInput,CreatePaymentResult,PaymentProvider,VerifyPaymentResult,WebhookVerificationResult} from "./types";
import {PaymentProviderError} from "./types";
const API="https://api.chapa.co/v1";
function secret(){const value=process.env.CHAPA_SECRET_KEY;if(!value)throw new PaymentProviderError("Chapa is not configured.","PROVIDER_NOT_CONFIGURED");return value;}
function safeEqualHex(a:string,b:string){try{const aa=Buffer.from(a,"hex"),bb=Buffer.from(b,"hex");return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb);}catch{return false}}
export class ChapaProvider implements PaymentProvider{
 name="chapa";
 async createPayment(input:CreatePaymentInput):Promise<CreatePaymentResult>{if(input.currency!=="ETB")throw new PaymentProviderError("Chapa checkout is configured for ETB only.","UNSUPPORTED_CURRENCY");const payload={amount:input.amount.toFixed(2),currency:input.currency,email:input.email,first_name:input.firstName,last_name:input.lastName,phone_number:input.phone,tx_ref:input.txRef,callback_url:input.callbackUrl,return_url:input.returnUrl,customization:{title:input.title,description:input.description||"Linqo purchase"},meta:input.metadata};const res=await fetch(`${API}/transaction/initialize`,{method:"POST",headers:{Authorization:`Bearer ${secret()}`,"Content-Type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});const json=await res.json().catch(()=>null) as any;if(!res.ok||!json?.data?.checkout_url)throw new PaymentProviderError("Chapa could not initialize the transaction.","INITIALIZE_FAILED");return{checkoutUrl:json.data.checkout_url,status:"pending",providerReference:json.data?.reference};}
 async verifyPayment(txRef:string):Promise<VerifyPaymentResult>{const res=await fetch(`${API}/transaction/verify/${encodeURIComponent(txRef)}`,{headers:{Authorization:`Bearer ${secret()}`},cache:"no-store"});const json=await res.json().catch(()=>null) as any;if(!res.ok||!json?.data)throw new PaymentProviderError("Chapa verification failed.","VERIFY_FAILED");const status=String(json.data.status||"").toLowerCase();return{txRef,providerReference:json.data.reference,amount:Number(json.data.amount),currency:String(json.data.currency),status:status==="success"?"paid":status==="failed"?"failed":status==="refunded"?"refunded":status==="cancelled"?"cancelled":"pending",raw:json};}
 async verifyWebhook(rawBody:string,headers:Headers):Promise<WebhookVerificationResult>{const webhookSecret=process.env.CHAPA_WEBHOOK_SECRET;if(!webhookSecret)return{valid:false};const x=headers.get("x-chapa-signature");const chapa=headers.get("chapa-signature");const payloadHash=crypto.createHmac("sha256",webhookSecret).update(rawBody).digest("hex");const secretHash=crypto.createHmac("sha256",webhookSecret).update(webhookSecret).digest("hex");const valid=Boolean((x&&safeEqualHex(payloadHash,x))||(chapa&&safeEqualHex(secretHash,chapa)));if(!valid)return{valid:false};const body=JSON.parse(rawBody) as any;return{valid:true,txRef:body.tx_ref||body.trx_ref,eventId:body.reference||`${body.event||"event"}:${body.tx_ref||"unknown"}`,raw:body};}
 async refundPayment():Promise<{status:"pending";raw:unknown}>{throw new PaymentProviderError("Refund initiation is not enabled in this Linqo Chapa adapter. Process refunds from the configured merchant workflow until the refund API is explicitly integrated.","OPERATION_NOT_SUPPORTED");}
}
