"use client";
import { ExternalLink, BadgeCheck, MoreHorizontal } from "lucide-react";
import type { LinkItem } from "@/types/database";

type PreviewProfile={display_name:string;bio?:string|null;avatar_url?:string|null;is_verified?:boolean;username?:string;appearance?:Record<string,unknown>};
export function ProfilePreview({profile,links,mode="mobile"}:{profile:PreviewProfile;links:Partial<LinkItem>[];mode?:"mobile"|"desktop"}){
  const a=profile.appearance||{};const bg=typeof a.backgroundColor==="string"?a.backgroundColor:"#f8f4ec";const text=typeof a.textColor==="string"?a.textColor:"#171a18";const button=typeof a.buttonColor==="string"?a.buttonColor:"#ffffff";const radius=a.buttonStyle==="square"?"10px":a.buttonStyle==="pill"?"999px":"18px";
  return <div className={`${mode==="mobile"?"mx-auto w-[320px] max-w-full rounded-[36px] border-[7px] border-[#1b1d1c]":"w-full rounded-[24px] border border-black/10"} overflow-hidden shadow-xl`}><div className={`${mode==="mobile"?"min-h-[620px]":"min-h-[480px]"} p-5 text-center`} style={{background:bg,color:text}}><div className="ml-auto grid size-8 place-items-center rounded-full bg-black/5"><MoreHorizontal size={16}/></div>{profile.avatar_url?<img src={profile.avatar_url} alt="" className="mx-auto mt-2 size-20 rounded-full object-cover"/>:<div className="mx-auto mt-2 grid size-20 place-items-center rounded-full bg-[#135d44] text-xl font-bold text-white">{profile.display_name.split(" ").map(v=>v[0]).join("").slice(0,2)||"L"}</div>}<div className="mt-4 flex items-center justify-center gap-1.5"><h3 className="text-xl font-bold">{profile.display_name||"Your name"}</h3>{profile.is_verified&&<BadgeCheck size={18} className="text-[#135d44]"/>}</div><p className="mx-auto mt-2 max-w-[260px] text-sm leading-5 opacity-65">{profile.bio||"Your bio will appear here."}</p><div className="mt-6 space-y-3">{links.filter(l=>l.is_enabled!==false).map((link)=><div key={link.id||link.title} className="flex min-h-14 items-center justify-between gap-3 px-4 py-3 text-left shadow-sm" style={{background:button,borderRadius:radius}}><span className="text-sm font-semibold">{link.title}</span><ExternalLink size={15} className="opacity-50"/></div>)}{links.length===0&&<div className="rounded-2xl border border-dashed border-black/15 p-5 text-sm opacity-55">Add your first link</div>}</div><div className="mt-8 text-[11px] font-semibold opacity-45">Linqo</div></div></div>
}
