"use client";
import { useEffect,useMemo,useState } from "react";
import { Check, Loader2, ArrowRight, ArrowLeft, Upload } from "lucide-react";
import { publicEnv } from "@/lib/env";
const categories=["Creator","Business","Freelancer","Artist","Musician","Professional","Student","Organization","Other"] as const;
const themes=["minimal","glass","creator","professional","business","dark","elegant"] as const;
const quickLinks=["Website","Instagram","TikTok","Telegram","YouTube","WhatsApp","Facebook","LinkedIn"];
const freeThemes=new Set<string>(["minimal","creator"]);
export function OnboardingFlow(){const[step,setStep]=useState(1);const[username,setUsername]=useState("");const[availability,setAvailability]=useState<"idle"|"checking"|"available"|"taken"|"invalid">("idle");const[displayName,setDisplayName]=useState("");const[bio,setBio]=useState("");const[category,setCategory]=useState<typeof categories[number]>("Creator");const[theme,setTheme]=useState<typeof themes[number]>("minimal");const[links,setLinks]=useState<Record<string,string>>({});const[avatar,setAvatar]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  useEffect(()=>{if(username.length<3){setAvailability("idle");return;}const id=setTimeout(async()=>{setAvailability("checking");const res=await fetch(`/api/onboarding/username?username=${encodeURIComponent(username)}`);const json=await res.json();setAvailability(res.ok?(json.available?"available":"taken"):"invalid");},350);return()=>clearTimeout(id);},[username]);
  const canNext=useMemo(()=>step===1?availability==="available":step===2?displayName.trim().length>0:true,[step,availability,displayName]);
  async function publish(){setBusy(true);setError("");const payload={username,displayName,bio,category,theme,links:Object.entries(links).filter(([,url])=>url.trim()).map(([title,url])=>({title,url,type:title==="WhatsApp"?"whatsapp":title==="Telegram"?"telegram":title==="Website"?"standard":"social"}))};const res=await fetch("/api/onboarding",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const json=await res.json();if(!res.ok){setError(json.error||"Unable to publish.");setBusy(false);return;}if(avatar){const fd=new FormData();fd.append("file",avatar);await fetch("/api/uploads/avatar",{method:"POST",body:fd});}window.location.assign("/dashboard");}
  return <div className="mx-auto w-full max-w-5xl"><div className="mb-8 flex items-center justify-between"><div><span className="text-xs font-bold uppercase tracking-[.14em] text-[#135d44]">Step {step} of 5</span><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Build your first Linqo</h1></div><div className="hidden text-sm text-[#6c756f] sm:block">{publicEnv.NEXT_PUBLIC_APP_URL.replace(/^https?:\/\//,"")}/{username||"username"}</div></div><div className="card soft-shadow overflow-hidden"><div className="h-1 bg-[#e6e9e3]"><div className="h-full bg-[#135d44] transition-all" style={{width:`${step*20}%`}}/></div><div className="p-6 sm:p-10">
    {step===1&&<section><h2 className="text-2xl font-semibold">Choose your username</h2><p className="mt-2 text-sm text-[#68716c]">Lowercase, memorable and permanent enough to print on a QR code.</p><div className="mt-7 flex items-center rounded-2xl border border-black/10 bg-white px-4"><span className="text-sm text-[#7b837f]">/</span><input autoFocus value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/\s/g,""))} maxLength={30} className="w-full bg-transparent px-2 py-4 outline-none" placeholder="mahir"/></div><div className="mt-3 text-sm">{availability==="checking"&&<span className="text-[#68716c]">Checking…</span>}{availability==="available"&&<span className="inline-flex items-center gap-1 text-[#135d44]"><Check size={15}/>Available</span>}{availability==="taken"&&<span className="text-[#b44343]">That username is taken.</span>}{availability==="invalid"&&<span className="text-[#b44343]">Use 3–30 lowercase letters, numbers, dots, hyphens or underscores.</span>}</div></section>}
    {step===2&&<section><h2 className="text-2xl font-semibold">Tell people who you are</h2><div className="mt-7 grid gap-5 sm:grid-cols-[120px_1fr]"><label className="grid aspect-square cursor-pointer place-items-center rounded-[28px] border border-dashed border-black/20 bg-[#f5f6f3] text-center text-xs font-semibold text-[#68716c]"><Upload className="mx-auto mb-2" size={20}/>Photo<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={e=>setAvatar(e.target.files?.[0]||null)}/></label><div className="space-y-4"><input value={displayName} onChange={e=>setDisplayName(e.target.value)} maxLength={80} placeholder="Display name" className="w-full rounded-2xl border border-black/10 px-4 py-3"/><textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={240} rows={3} placeholder="Short bio" className="w-full rounded-2xl border border-black/10 px-4 py-3"/><select value={category} onChange={e=>setCategory(e.target.value as typeof category)} className="w-full rounded-2xl border border-black/10 px-4 py-3">{categories.map(c=><option key={c}>{c}</option>)}</select></div></div></section>}
    {step===3&&<section><h2 className="text-2xl font-semibold">Add your first links</h2><p className="mt-2 text-sm text-[#68716c]">Skip any channel you do not use.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{quickLinks.map(name=><label key={name} className="text-sm font-semibold">{name}<input value={links[name]||""} onChange={e=>setLinks({...links,[name]:e.target.value})} placeholder={name==="WhatsApp"?"https://wa.me/251...":"https://"} className="mt-2 w-full rounded-2xl border border-black/10 px-4 py-3 font-normal"/></label>)}</div></section>}
    {step===4&&<section><h2 className="text-2xl font-semibold">Pick a starting theme</h2><p className="mt-2 text-sm text-[#68716c]">You can change every visual detail later.</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{themes.map(t=><button key={t} onClick={()=>freeThemes.has(t)&&setTheme(t)} disabled={!freeThemes.has(t)} className={`relative aspect-[4/5] rounded-[24px] border p-3 text-left ${theme===t?"border-[#135d44] ring-2 ring-[#135d44]/20":"border-black/10"} disabled:cursor-not-allowed disabled:opacity-55`}><div className={`h-3/4 rounded-2xl ${t==="dark"?"bg-[#181b19]":t==="glass"?"bg-gradient-to-br from-[#d6e7dd] to-[#e7d9bc]":"bg-[#eef1ea]"}`}/><b className="mt-3 block capitalize">{t}</b>{!freeThemes.has(t)&&<span className="absolute right-3 top-3 rounded-full bg-black/70 px-2 py-1 text-[10px] font-bold text-white">PRO</span>}</button>)}</div><p className="mt-4 text-xs text-[#68716c]">Premium themes unlock after a verified Pro or Business subscription.</p></section>}
    {step===5&&<section className="text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-[#e6f0ea] text-[#135d44]"><Check size={28}/></div><h2 className="mt-5 text-3xl font-semibold">Ready to publish.</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#68716c]">Your public page will use the username <b>{username}</b>. You can edit links, themes, visibility and analytics from the dashboard.</p><div className="mx-auto mt-6 max-w-md rounded-2xl bg-[#f3f5f1] p-4 text-sm font-semibold">{publicEnv.NEXT_PUBLIC_APP_URL.replace(/\/$/,"")}/{username}</div>{error&&<p className="mt-4 text-sm text-[#b44343]">{error}</p>}<button onClick={publish} disabled={busy} className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#135d44] px-6 py-3 text-sm font-semibold text-white">{busy&&<Loader2 className="animate-spin" size={16}/>}Publish my Linqo</button></section>}
    {step<5&&<div className="mt-9 flex justify-between"><button onClick={()=>setStep(Math.max(1,step-1))} disabled={step===1} className="inline-flex items-center gap-2 rounded-full px-4 py-3 text-sm font-semibold disabled:opacity-30"><ArrowLeft size={16}/>Back</button><button onClick={()=>setStep(Math.min(5,step+1))} disabled={!canNext} className="inline-flex items-center gap-2 rounded-full bg-[#135d44] px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Continue<ArrowRight size={16}/></button></div>}
  </div></div></div>;
}
