import { getCurrentProfile } from "@/lib/data";
import { MiniChart } from "@/components/dashboard/mini-chart";
import { StatCard } from "@/components/dashboard/stat-card";
import { entitlements, getPlan } from "@/lib/entitlements";
function validDate(v?:string){return v&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v:null}
export default async function Analytics({searchParams}:{searchParams:Promise<{range?:string;start?:string;end?:string}>}){
  const q=await searchParams;const{profile,supabase}=await getCurrentProfile();const plan=await getPlan(supabase,profile.id);const advanced=entitlements[plan].customAnalytics;
  const end=advanced&&validDate(q.end)||new Date().toISOString().slice(0,10);const preset=q.range==="7"?7:30;const start=advanced&&validDate(q.start)||new Date(Date.now()-(preset-1)*86400000).toISOString().slice(0,10);
  const[{data:daily},{data:links},{data:refs},{data:devices}]=await Promise.all([supabase.from("analytics_daily").select("day,profile_views,link_clicks,product_purchases,revenue").eq("profile_id",profile.id).gte("day",start).lte("day",end).order("day"),supabase.from("link_daily_stats").select("link_id,clicks,links(title)").eq("profile_id",profile.id).gte("day",start).lte("day",end),supabase.from("referrer_daily_stats").select("referrer_domain,events").eq("profile_id",profile.id).gte("day",start).lte("day",end),supabase.from("device_daily_stats").select("device_type,events").eq("profile_id",profile.id).gte("day",start).lte("day",end)]);
  const views=(daily||[]).reduce((s,r)=>s+Number(r.profile_views),0),clicks=(daily||[]).reduce((s,r)=>s+Number(r.link_clicks),0),revenue=(daily||[]).reduce((s,r)=>s+Number(r.revenue),0);const topLinks=new Map<string,{title:string;clicks:number}>();for(const r of links||[]){const id=r.link_id;const title=(r.links as any)?.title||"Link";const prev=topLinks.get(id)||{title,clicks:0};prev.clicks+=Number(r.clicks);topLinks.set(id,prev)}const topRefs=new Map<string,number>();for(const r of refs||[])topRefs.set(r.referrer_domain,(topRefs.get(r.referrer_domain)||0)+Number(r.events));const devMap=new Map<string,number>();for(const r of devices||[])devMap.set(r.device_type,(devMap.get(r.device_type)||0)+Number(r.events));
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#135d44]">Analytics</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.04em]">Understand what earns attention.</h1><p className="mt-2 text-sm text-[#68716c]">Aggregated production analytics from {start} to {end}. {advanced?"Custom ranges are enabled.":"Free plan includes 7 and 30 day standard views."}</p></div>{advanced?<form className="flex flex-wrap items-end gap-2"><label className="text-xs font-semibold">From<input name="start" type="date" defaultValue={start} className="mt-1 block rounded-xl border border-black/10 bg-white px-3 py-2 text-sm"/></label><label className="text-xs font-semibold">To<input name="end" type="date" defaultValue={end} className="mt-1 block rounded-xl border border-black/10 bg-white px-3 py-2 text-sm"/></label><button className="rounded-full bg-[#135d44] px-4 py-2.5 text-xs font-semibold text-white">Apply</button></form>:<div className="flex gap-2"><a href="?range=7" className="btn-secondary">7 days</a><a href="?range=30" className="btn-secondary">30 days</a></div>}</div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Views" value={views}/><StatCard label="Clicks" value={clicks}/><StatCard label="CTR" value={views?`${((clicks/views)*100).toFixed(1)}%`:"—"}/><StatCard label="Revenue" value={revenue?`ETB ${revenue.toLocaleString()}`:"—"}/></div><div className="mt-6 grid gap-5 xl:grid-cols-2"><section className="card p-6"><h2 className="font-semibold">Daily views</h2><div className="mt-6"><MiniChart values={(daily||[]).map(r=>Number(r.profile_views))}/></div></section><section className="card p-6"><h2 className="font-semibold">Top links</h2><div className="mt-5 space-y-3">{[...topLinks.values()].sort((a,b)=>b.clicks-a.clicks).slice(0,8).map((r,i)=><div key={`${r.title}-${i}`} className="flex justify-between border-b border-black/[.06] pb-3 text-sm"><span className="truncate pr-4">{r.title}</span><b>{r.clicks}</b></div>)}{topLinks.size===0&&<p className="text-sm text-[#68716c]">No link clicks in this range.</p>}</div></section><section className="card p-6"><h2 className="font-semibold">Top referrers</h2><div className="mt-5 space-y-3">{[...topRefs.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([name,count])=><div key={name} className="flex justify-between text-sm"><span>{name}</span><b>{count}</b></div>)}{topRefs.size===0&&<p className="text-sm text-[#68716c]">No referrer data in this range.</p>}</div></section><section className="card p-6"><h2 className="font-semibold">Devices</h2><div className="mt-5 grid grid-cols-3 gap-3">{["mobile","desktop","tablet"].map(d=><div key={d} className="rounded-2xl bg-[#f1f3ef] p-4 text-center"><div className="text-2xl font-semibold">{devMap.get(d)||0}</div><div className="mt-1 text-xs capitalize text-[#737c77]">{d}</div></div>)}</div></section></div></div>
}
